name: ci

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    paths-ignore:
      - '**.md'

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Silencing git over hex tag names
        run: "git config --global advice.objectNameWarning false"
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - name: Running asdf's plugin-test for latest
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: kuttl version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Running asdf's plugin-test for specific version
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: kuttl version
          version: ref:d2cd0d5ec86a758ca4a13db032a89ae214d3d524
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
